---
- name: Create elasticsearch docker directory
  file:
    path: /opt/docker-services/elk
    state: directory
  become: yes
  tags: install elasticsearch latest


- name: Copy directory
  copy:
    src: "logstash"
    dest: /opt/docker-services/elk
  become: yes
  tags: install elasticsearch latest


- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml
    dest: /opt/docker-services/elk/docker-compose.yml
  become: yes
  tags: install elasticsearch latest

